/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import java.util.Scanner;
import java.util.UUID;
import java.io.IOException;
import org.example.service.UserBookingService;
import org.example.entities.User;
import org.example.entities.Train;
import org.example.util.UserServiceUtil;

public class App {

    public static void main(String[] args) {

        System.out.println("Running Train Booking System");
        Scanner sc=new Scanner(System.in);
        int option=0;
        UserBookingService userBookingService;

        try{
            userBookingService=new UserBookingService();
        }
        catch(IOException ex){
            System.out.println("Error initializing UserBookingService: " + ex.getMessage());
            ex.printStackTrace();
            return;

        }
while(option !=7)
        {
            System.out.print("Enter your choice: ");
            if (sc.hasNextInt()) {
                option = sc.nextInt();
                sc.nextLine(); // Consume newline
            } else {
                System.out.println("No input available. Exiting...");
                break;
            }

            switch(option)
            {
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp=sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp=sc.next();
                    User userToSignUp=new User(nameToSignUp,passwordToSignUp,UserServiceUtil.hashPassword(passwordToSignUp),new ArrayList<>(),UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToLogin = sc.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    }catch (IOException ex){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Enter your source station name");
                    String source=sc.next();
                    System.out.println("Enter your destination name");
                    String destination=sc.next();

                    try {
                        List<Train> trains=userBookingService.getTrains(source,destination);
                        int index=1;
                        for(Train t : trains)
                        {
                            System.out.println(index+" TrainId: "+t.getTrainId());
                            System.out.println("Train Info: " + t.getTrainInfo());
                            index++;
                        }
                    } catch (IOException e) {
                        System.out.println("Error searching trains: " + e.getMessage());
                    }
                break;
                
                default:
                    System.out.println("Invalid option");
                    break;
            }

        }
    }
    
    public String getGreeting() {
        return "Hello World!";
    }
}
